### ISSUE TITLE
Could you add the code of the models involved in PatchTST and others showed in main tables to the code repository?

### ISSUE THREAD

**Issue by OneStep758** [SalesforceAIResearch/pretrain-time-series-cloudops#1]
Hello, it's nice to see your excellent work. I hope to run the models involved in the main tables such as PatchTST in your framework. Can you add this part of the code to the code repository?

**Comment by gorold** [comment]
Hey, thanks for the interest. Sure, I could work on adding these models to the repo - any particular models that you're looking at apart from PatchTST? It might take some time to add everything depending on my bandwidth.
