### ISSUE TITLE
load Azure dataset successfully, but cannot load the alibaba and borg datasets

### ISSUE THREAD

**Issue by starry44** [SalesforceAIResearch/pretrain-time-series-cloudops#2]
Hi，
Thanks for your code! I load the azure dataset successfully. However, when I try to load the alibaba and borg dataset, an error occurred:
![WechatIMG7](https://github.com/SalesforceAIResearch/pretrain-time-series-cloudops/assets/55570236/10cedf52-d883-4517-b5b9-e3c26d1bd11a)
I load data using the official implementation in 'pretrain_exp.py' by def 'load dataset' and modify "dataset_name" to "borg_cluster_data_2011" or "alibaba_cluster_trace_2018".
I'm wondering if something went wrong. Thanks!

**Comment by gorold** [comment]
It's working fine on my end, you might want to clear your huggingface datasets cache and try again.

**Comment by starry44** [comment]
> It's working fine on my end, you might want to clear your huggingface datasets cache and try again.

Thanks for your reply! It's about the version of package 'datasets'. I use the right version and it works.
