### ISSUE TITLE
Target normalization

### ISSUE THREAD

**Issue by pinyinzimu** [SalesforceAIResearch/pretrain-time-series-cloudops#3]
Hi, thanks for your great work. According to the paper, instance normalization is used for both input target and output prediction, but I didn't find any code line related to this. Could you please give me some help?

**Comment by gorold** [comment]
Input normalization - https://github.com/SalesforceAIResearch/pretrain-time-series-cloudops/blob/bf24685d894fe41973d20831430ef6a0324b5d54/pretraining/model/backbone/masked_encoder.py#L273-L274

Output normalization (loss) - https://github.com/SalesforceAIResearch/pretrain-time-series-cloudops/blob/bf24685d894fe41973d20831430ef6a0324b5d54/pretraining/model/backbone/masked_encoder.py#L451

Output normalization (predict) - https://github.com/SalesforceAIResearch/pretrain-time-series-cloudops/blob/bf24685d894fe41973d20831430ef6a0324b5d54/pretraining/model/backbone/masked_encoder.py#L543
